unit BGRASVGImageList;

{$mode delphi}

interface

uses
  Classes, SysUtils, LResources, Forms, Controls, Graphics, ImgList, Dialogs, FGL,
  XMLConf, BGRABitmap, BGRABitmapTypes, BGRASVG;

type

  TListOfTStringList = TFPGObjectList<TStringList>;

  { TBGRASVGImageList }

  TBGRASVGImageList = class(TComponent)
  private
    FHeight: integer;
    FHorizontalAlignment: TAlignment;
    FItems: TListOfTStringList;
    FReferenceDPI: integer;
    FTargetRasterImageList: TImageList;
    FUseSVGAlignment: boolean;
    FVerticalAlignment: TTextLayout;
    FWidth: integer;
    FRasterized: boolean;
    FDataLineBreak: TTextLineBreakStyle;
    procedure ReadData(Stream: TStream);
    procedure SetHeight(AValue: integer);
    procedure SetTargetRasterImageList(AValue: TImageList);
    procedure SetWidth(AValue: integer);
    procedure WriteData(Stream: TStream);
  protected
    procedure Load(const XMLConf: TXMLConfig);
    procedure Save(const XMLConf: TXMLConfig);
    procedure DefineProperties(Filer: TFiler); override;
    function GetCount: integer;
    // Get SVG string
    function GetSVGString(AIndex: integer): string; overload;
    procedure Rasterize; virtual;
    procedure RasterizeIfNeeded;
    procedure QueryRasterize;
  public
    constructor Create(AOwner: TComponent); override;
    destructor Destroy; override;
    function Add(ASVG: string): integer;
    procedure Remove(AIndex: integer);
    procedure Exchange(AIndex1, AIndex2: integer);
    procedure Replace(AIndex: integer; ASVG: string);
    function GetScaledSize(ATargetDPI: integer): TSize;
    // Get TBGRABitmap with custom width and height
    function GetBGRABitmap(AIndex: integer; AWidth, AHeight: integer): TBGRABitmap; overload;
    function GetBGRABitmap(AIndex: integer; AWidth, AHeight: integer;
      AUseSVGAlignment: boolean): TBGRABitmap; overload;
    // Get TBitmap with custom width and height
    function GetBitmap(AIndex: integer; AWidth, AHeight: integer): TBitmap; overload;
    function GetBitmap(AIndex: integer; AWidth, AHeight: integer;
      AUseSVGAlignment: boolean): TBitmap; overload;
    // Draw image with custom width and height. The Width and
    // Height property are in LCL coordinates.
    procedure Draw(AIndex: integer; AControl: TControl; ACanvas: TCanvas;
      ALeft, ATop, AWidth, AHeight: integer); overload;
    procedure Draw(AIndex: integer; AControl: TControl; ACanvas: TCanvas;
      ALeft, ATop, AWidth, AHeight: integer; AUseSVGAlignment: boolean;
      AOpacity: byte = 255); overload;
    // Draw image with custom width, height and canvas scale. The Width and
    // Height property are in LCL coordinates. CanvasScale is useful on MacOS
    // where LCL coordinates do not match actual pixels.
    procedure Draw(AIndex: integer; ACanvasScale: single; ACanvas: TCanvas;
      ALeft, ATop, AWidth, AHeight: integer); overload;
    procedure Draw(AIndex: integer; ACanvasScale: single; ACanvas: TCanvas;
      ALeft, ATop, AWidth, AHeight: integer; AUseSVGAlignment: boolean;
      AOpacity: byte = 255); overload;
    // Draw on the target BGRABitmap with specified Width and Height.
    procedure Draw(AIndex: integer; ABitmap: TBGRABitmap; const ARectF: TRectF); overload;
    procedure Draw(AIndex: integer; ABitmap: TBGRABitmap; const ARectF: TRectF;
      AUseSVGAlignment: boolean); overload;

    // Generate bitmaps for an image list
    procedure PopulateImageList(const AImageList: TImageList; AWidths: array of integer);
    property SVGString[AIndex: integer]: string read GetSVGString;
    property Count: integer read GetCount;
  published
    property Width: integer read FWidth write SetWidth;
    property Height: integer read FHeight write SetHeight;
    property ReferenceDPI: integer read FReferenceDPI write FReferenceDPI default 96;
    property UseSVGAlignment: boolean read FUseSVGAlignment write FUseSVGAlignment default False;
    property HorizontalAlignment: TAlignment read FHorizontalAlignment write FHorizontalAlignment default taCenter;
    property VerticalAlignment: TTextLayout read FVerticalAlignment write FVerticalAlignment default tlCenter;
    property TargetRasterImageList: TImageList read FTargetRasterImageList write SetTargetRasterImageList default nil;
  end;

type
  TSVGResolutionWidths = array of integer;

  { TBGRASVGRasterImageList

    A standard image list whose raster entries are generated by an internal
    TBGRASVGImageList. The original SVG-only component remains unchanged. }

  TBGRASVGRasterImageList = class(TImageList)
  private
    FSVGSource: TBGRASVGImageList;
    FChangeLink: TChangeLink;
    FBuilding: boolean;
    FDestroying: boolean;
    FRequestedWidths: TSVGResolutionWidths;
    function GetImageWidth: integer;
    function GetImageHeight: integer;
    procedure SetImageWidth(AValue: integer);
    procedure SetImageHeight(AValue: integer);
    function GetSVGCount: integer;
    function GetSVGString(AIndex: integer): string;
    function GetSVGWidths: TSVGResolutionWidths;
    procedure ImageListChanged(Sender: TObject);
    procedure RasterizeSVG;
    procedure RebuildSVG;
    procedure ReadSVGItems(Stream: TStream);
    procedure WriteSVGItems(Stream: TStream);
  protected
    procedure DefineProperties(Filer: TFiler); override;
    procedure Loaded; override;
  public
    constructor Create(AOwner: TComponent); override;
    destructor Destroy; override;
    function AddSVG(const ASVG: string): integer;
    procedure RemoveSVG(AIndex: integer);
    procedure ReplaceSVG(AIndex: integer; const ASVG: string);
    procedure ExchangeSVG(AIndex1, AIndex2: integer);
    procedure ClearSVG;
    procedure RegisterResolutions(const AResolutionWidths: array of integer); override;
    property SVGCount: integer read GetSVGCount;
    property SVGString[AIndex: integer]: string read GetSVGString;
  published
    property Width: integer read GetImageWidth write SetImageWidth default 16;
    property Height: integer read GetImageHeight write SetImageHeight default 16;
    property Scaled default True;
  end;

procedure Register;

implementation

uses LCLType, XMLRead;

type
  TSVGSourceForRasterList = class(TBGRASVGImageList)
  protected
    procedure Rasterize; override;
  end;

procedure TSVGSourceForRasterList.Rasterize;
begin
  TBGRASVGRasterImageList(Owner).RasterizeSVG;
end;

procedure Register;
begin
  RegisterComponents('BGRA Themes', [TBGRASVGImageList, TBGRASVGRasterImageList]);
end;

{$IF FPC_FULLVERSION < 30203}
type

  { TPatchedXMLConfig }

  TPatchedXMLConfig = class(TXMLConfig)
    public
      procedure LoadFromStream(S : TStream); reintroduce;
  end;


{ TPatchedXMLConfig }

procedure TPatchedXMLConfig.LoadFromStream(S: TStream);
begin
  FreeAndNil(Doc);
  ReadXMLFile(Doc,S);
  FModified := False;
  if (Doc.DocumentElement.NodeName<>RootName) then
    raise EXMLConfigError.CreateFmt(SWrongRootName,[RootName,Doc.DocumentElement.NodeName]);
end;
{$ENDIF}
{ TBGRASVGImageList }

procedure TBGRASVGImageList.ReadData(Stream: TStream);

  // Detects EOL marker used in the text stream
  function GetLineEnding(AStream: TStream; AMaxLookAhead: integer = 4096): TTextLineBreakStyle;
  var c: char;
    i: integer;
  begin
    c := #0;
    for i := 0 to AMaxLookAhead-1 do
    begin
      if AStream.Read(c, sizeof(c)) = 0 then break;
      Case c of
      #10: exit(tlbsLF);
      #13: begin
          if AStream.Read(c, sizeof(c)) = 0 then c := #0;
          if c = #10 then
            exit(tlbsCRLF)
          else
            exit(tlbsCR);
        end;
      end;
    end;
    // no marker found, return system default
    exit(DefaultTextLineBreakStyle);
  end;

var
  FXMLConf: TXMLConfig;
begin
  FXMLConf := TXMLConfig.Create(Self);
  try
    // Detect the line EOL marker
    Stream.Position := 0;
    FDataLineBreak:= GetLineEnding(Stream);
    // Actually load the XML file
    Stream.Position := 0;
    {$IF FPC_FULLVERSION < 30203}TPatchedXMLConfig(FXMLConf){$ELSE}FXMLConf{$ENDIF}.LoadFromStream(Stream);
    Load(FXMLConf);
  finally
    FXMLConf.Free;
  end;
end;

procedure TBGRASVGImageList.SetHeight(AValue: integer);
begin
  if FHeight = AValue then
    Exit;
  FHeight := AValue;
  QueryRasterize;
end;

procedure TBGRASVGImageList.SetTargetRasterImageList(AValue: TImageList);
begin
  if FTargetRasterImageList=AValue then Exit;
  if Assigned(FTargetRasterImageList) then FTargetRasterImageList.Clear;
  FTargetRasterImageList:=AValue;
  QueryRasterize;
end;

procedure TBGRASVGImageList.SetWidth(AValue: integer);
begin
  if FWidth = AValue then
    Exit;
  FWidth := AValue;
  QueryRasterize;
end;

procedure TBGRASVGImageList.WriteData(Stream: TStream);
var
  FXMLConf: TXMLConfig;
  FTempStream: TStringStream;
  FNormalizedData: string;
begin
  FXMLConf := TXMLConfig.Create(Self);
  FTempStream := TStringStream.Create;
  try
    Save(FXMLConf);
    // Save to temporary string stream.
    // EOL marker will depend on OS (#13#10 or #10),
    // because TXMLConfig automatically changes EOL to platform default.
    FXMLConf.SaveToStream(FTempStream);
    // Normalize EOL marker, as data will be saved as binary data.
    // Saving without normalization would lead to different binary
    // data when saving on different platforms.
    FNormalizedData := AdjustLineBreaks(FTempStream.DataString, FDataLineBreak);
    if FNormalizedData <> '' then
      Stream.WriteBuffer(FNormalizedData[1], Length(FNormalizedData));
    FXMLConf.Flush;
  finally
    FXMLConf.Free;
    FTempStream.Free;
  end;
end;

procedure TBGRASVGImageList.Load(const XMLConf: TXMLConfig);
var
  i, j, index: integer;
begin
  try
    FItems.Clear;
    j := XMLConf.GetValue('Count', 0);
    for i := 0 to j - 1 do
    begin
      index := FItems.Add(TStringList.Create);
      FItems[index].Text := XMLConf.GetValue('Item' + i.ToString + '/SVG', '');
    end;
  finally
  end;
end;

procedure TBGRASVGImageList.Save(const XMLConf: TXMLConfig);
var
  i: integer;
begin
  try
    XMLConf.SetValue('Count', FItems.Count);
    for i := 0 to FItems.Count - 1 do
      XMLConf.SetValue('Item' + i.ToString + '/SVG', AdjustLineBreaks(FItems[i].Text, FDataLineBreak));
  finally
  end;
end;

procedure TBGRASVGImageList.DefineProperties(Filer: TFiler);
begin
  inherited DefineProperties(Filer);
  Filer.DefineBinaryProperty('Items', ReadData, WriteData, True);
end;

constructor TBGRASVGImageList.Create(AOwner: TComponent);
begin
  inherited Create(AOwner);
  FItems := TListOfTStringList.Create(True);
  FWidth := 16;
  FHeight := 16;
  FReferenceDPI := 96;
  FUseSVGAlignment:= false;
  FHorizontalAlignment := taCenter;
  FVerticalAlignment := tlCenter;
  FDataLineBreak := DefaultTextLineBreakStyle;
end;

destructor TBGRASVGImageList.Destroy;
begin
  FItems.Free;
  inherited Destroy;
end;

function TBGRASVGImageList.Add(ASVG: string): integer;
var
  list: TStringList;
begin
  list := TStringList.Create;
  list.Text := ASVG;
  Result := FItems.Add(list);
  QueryRasterize;
end;

procedure TBGRASVGImageList.Remove(AIndex: integer);
begin
  FItems.Remove(FItems[AIndex]);
  QueryRasterize;
end;

procedure TBGRASVGImageList.Exchange(AIndex1, AIndex2: integer);
begin
  FItems.Exchange(AIndex1, AIndex2);
  QueryRasterize;
end;

function TBGRASVGImageList.GetSVGString(AIndex: integer): string;
begin
  Result := FItems[AIndex].Text;
end;

procedure TBGRASVGImageList.Rasterize;
begin
  if Assigned(FTargetRasterImageList) then
  begin
    FTargetRasterImageList.Clear;
    FTargetRasterImageList.Width := Width;
    FTargetRasterImageList.Height := Height;
    {$IFDEF DARWIN}
    PopulateImageList(FTargetRasterImageList, [Width, Width*2]);
    {$ELSE}
    PopulateImageList(FTargetRasterImageList, [Width]);
    {$ENDIF}
  end;
end;

procedure TBGRASVGImageList.RasterizeIfNeeded;
begin
  if not FRasterized then
  begin
    Rasterize;
    FRasterized := true;
  end;
end;

procedure TBGRASVGImageList.QueryRasterize;
var method: TThreadMethod;
begin
  FRasterized := false;
  method := RasterizeIfNeeded;
  TThread.ForceQueue(nil, method);
end;

procedure TBGRASVGImageList.Replace(AIndex: integer; ASVG: string);
begin
  FItems[AIndex].Text := ASVG;
  QueryRasterize;
end;

function TBGRASVGImageList.GetCount: integer;
begin
  Result := FItems.Count;
end;

function TBGRASVGImageList.GetScaledSize(ATargetDPI: integer): TSize;
begin
  result.cx := MulDiv(Width, ATargetDPI, ReferenceDPI);
  result.cy := MulDiv(Height, ATargetDPI, ReferenceDPI);
end;

function TBGRASVGImageList.GetBGRABitmap(AIndex: integer; AWidth,
  AHeight: integer): TBGRABitmap;
begin
  result := GetBGRABitmap(AIndex, AWidth, AHeight, UseSVGAlignment);
end;

function TBGRASVGImageList.GetBGRABitmap(AIndex: integer; AWidth, AHeight: integer;
  AUseSVGAlignment: boolean): TBGRABitmap;
var
  bmp: TBGRABitmap;
  svg: TBGRASVG;
begin
  bmp := TBGRABitmap.Create(AWidth, AHeight);
  svg := TBGRASVG.CreateFromString(FItems[AIndex].Text);
  try
    svg.StretchDraw(bmp.Canvas2D, 0, 0, AWidth, AHeight, AUseSVGAlignment);
  finally
    svg.Free;
  end;
  Result := bmp;
end;

function TBGRASVGImageList.GetBitmap(AIndex: integer; AWidth, AHeight: integer): TBitmap;
begin
  result := GetBitmap(AIndex, AWidth, AHeight, UseSVGAlignment);
end;

function TBGRASVGImageList.GetBitmap(AIndex: integer; AWidth, AHeight: integer;
  AUseSVGAlignment: boolean): TBitmap;
var
  bmp: TBGRABitmap;
  ms: TMemoryStream;
begin
  bmp := GetBGRABitmap(AIndex, AWidth, AHeight, AUseSVGAlignment);
  ms := TMemoryStream.Create;
  bmp.Bitmap.SaveToStream(ms);
  bmp.Free;
  Result := TBitmap.Create;
  ms.Position := 0;
  Result.LoadFromStream(ms);
  ms.Free;
end;

procedure TBGRASVGImageList.Draw(AIndex: integer; AControl: TControl;
  ACanvas: TCanvas; ALeft, ATop, AWidth, AHeight: integer);
begin
  Draw(AIndex, AControl, ACanvas, ALeft, ATop, AWidth, AHeight, UseSVGAlignment);
end;

procedure TBGRASVGImageList.Draw(AIndex: integer; AControl: TControl; ACanvas: TCanvas;
  ALeft, ATop, AWidth, AHeight: integer; AUseSVGAlignment: boolean; AOpacity: byte);
begin
  Draw(AIndex, AControl.GetCanvasScaleFactor, ACanvas, ALeft, ATop, AWidth, AHeight,
       AUseSVGAlignment, AOpacity);
end;

procedure TBGRASVGImageList.Draw(AIndex: integer; ACanvasScale: single;
  ACanvas: TCanvas; ALeft, ATop, AWidth, AHeight: integer);
begin
  Draw(AIndex, ACanvasScale, ACanvas, ALeft, ATop, AWidth, AHeight, UseSVGAlignment);
end;

procedure TBGRASVGImageList.Draw(AIndex: integer; ACanvasScale: single; ACanvas: TCanvas;
  ALeft, ATop, AWidth, AHeight: integer; AUseSVGAlignment: boolean; AOpacity: byte);
var
  bmp: TBGRABitmap;
begin
  if (AWidth = 0) or (AHeight = 0) or (ACanvasScale = 0) then
    Exit;
  bmp := TBGRABitmap.Create(round(AWidth * ACanvasScale), round(AHeight * ACanvasScale));
  try
    Draw(AIndex, bmp, rectF(0, 0, bmp.Width, bmp.Height), AUseSVGAlignment);
    bmp.ApplyGlobalOpacity(AOpacity);
    bmp.Draw(ACanvas, RectWithSize(ALeft, ATop, AWidth, AHeight), False);
  finally
    bmp.Free;
  end;
end;

procedure TBGRASVGImageList.Draw(AIndex: integer; ABitmap: TBGRABitmap; const ARectF: TRectF);
begin
  Draw(AIndex, ABitmap, ARectF, UseSVGAlignment);
end;

procedure TBGRASVGImageList.Draw(AIndex: integer; ABitmap: TBGRABitmap; const ARectF: TRectF;
  AUseSVGAlignment: boolean);
var
  svg: TBGRASVG;
begin
  svg := TBGRASVG.CreateFromString(FItems[AIndex].Text);
  try
    if AUseSVGAlignment then
      svg.StretchDraw(ABitmap.Canvas2D, ARectF, true)
      else svg.StretchDraw(ABitmap.Canvas2D, HorizontalAlignment, VerticalAlignment, ARectF.Left, ARectF.Top, ARectF.Width, ARectF.Height);
  finally
    svg.Free;
  end;
end;

procedure TBGRASVGImageList.PopulateImageList(const AImageList: TImageList;
  AWidths: array of integer);
var
  i, j: integer;
  arr: array of TCustomBitmap;
begin
  AImageList.Width := AWidths[0];
  AImageList.Height := MulDiv(AWidths[0], Height, Width);
  AImageList.Scaled := True;
  AImageList.RegisterResolutions(AWidths);
  SetLength({%H-}arr, Length(AWidths));
  for j := 0 to Count - 1 do
  begin
    for i := 0 to Length(arr) - 1 do
      arr[i] := GetBitmap(j, AWidths[i], MulDiv(AWidths[i], Height, Width), True);
    AImageList.AddMultipleResolutions(arr);
    for i := 0 to Length(arr) - 1 do
      TBitmap(Arr[i]).Free;
  end;
end;

{ TBGRASVGRasterImageList }

constructor TBGRASVGRasterImageList.Create(AOwner: TComponent);
begin
  inherited Create(AOwner);
  Scaled := True;
  FSVGSource := TSVGSourceForRasterList.Create(Self);
  FChangeLink := TChangeLink.Create;
  FChangeLink.OnChange := ImageListChanged;
  RegisterChanges(FChangeLink);
  FSVGSource.TargetRasterImageList := Self;
end;

destructor TBGRASVGRasterImageList.Destroy;
begin
  FDestroying := true;
  if Assigned(FChangeLink) then UnRegisterChanges(FChangeLink);
  FChangeLink.Free;
  if Assigned(FSVGSource) then
    TThread.RemoveQueuedEvents(nil, FSVGSource.RasterizeIfNeeded);
  FreeAndNil(FSVGSource);
  inherited Destroy;
end;

function TBGRASVGRasterImageList.GetImageWidth: integer;
begin
  Result := TImageList(Self).Width;
end;

function TBGRASVGRasterImageList.GetImageHeight: integer;
begin
  Result := TImageList(Self).Height;
end;

procedure TBGRASVGRasterImageList.SetImageWidth(AValue: integer);
begin
  if AValue <= 0 then raise EArgumentException.Create('Image width must be positive');
  if AValue = Width then Exit;
  SetWidthHeight(AValue, Height);
  RebuildSVG;
end;

procedure TBGRASVGRasterImageList.SetImageHeight(AValue: integer);
begin
  if AValue <= 0 then raise EArgumentException.Create('Image height must be positive');
  if AValue = Height then Exit;
  SetWidthHeight(Width, AValue);
  RebuildSVG;
end;

function TBGRASVGRasterImageList.GetSVGCount: integer;
begin
  if Assigned(FSVGSource) then Result := FSVGSource.Count else Result := 0;
end;

function TBGRASVGRasterImageList.GetSVGString(AIndex: integer): string;
begin
  Result := FSVGSource.SVGString[AIndex];
end;

function TBGRASVGRasterImageList.GetSVGWidths: TSVGResolutionWidths;
var
  i, j, n, value, base: integer;
  procedure AddWidth(AWidth: integer);
  var k: integer;
  begin
    if AWidth < base then Exit;
    for k := 0 to n - 1 do if Result[k] = AWidth then Exit;
    Result[n] := AWidth;
    Inc(n);
  end;
begin
  base := Width;
  SetLength(Result, 4 + Length(FRequestedWidths));
  n := 0;
  AddWidth(base);
  AddWidth(MulDiv(base, 125, 100));
  AddWidth(MulDiv(base, 150, 100));
  AddWidth(base * 2);
  for i := 0 to High(FRequestedWidths) do AddWidth(FRequestedWidths[i]);
  SetLength(Result, n);
  for i := 1 to n - 1 do
  begin
    value := Result[i];
    j := i - 1;
    while (j >= 0) and (Result[j] > value) do
    begin
      Result[j + 1] := Result[j];
      Dec(j);
    end;
    Result[j + 1] := value;
  end;
end;

procedure TBGRASVGRasterImageList.ImageListChanged(Sender: TObject);
begin
  if FBuilding or FDestroying or not Assigned(FSVGSource) or
     (csLoading in ComponentState) then Exit;
  // This also observes changes made through a TImageList reference.
  if (FSVGSource.Width <> Width) or (FSVGSource.Height <> Height) then
  begin
    // TImageList discards registered resolutions when its base size changes.
    FRequestedWidths := nil;
    FSVGSource.FWidth := Width;
    FSVGSource.FHeight := Height;
    FSVGSource.QueryRasterize;
  end
  else if (Count = 0) and (SVGCount > 0) then
    ClearSVG;
end;

procedure TBGRASVGRasterImageList.RasterizeSVG;
var
  widths: TSVGResolutionWidths;
  savedScaled: boolean;
begin
  if FBuilding or FDestroying or (csLoading in ComponentState) then Exit;
  FBuilding := true;
  BeginUpdate;
  try
    savedScaled := Scaled;
    widths := GetSVGWidths;
    inherited Clear;
    try
      FSVGSource.PopulateImageList(FSVGSource.TargetRasterImageList, widths);
    finally
      Scaled := savedScaled;
    end;
  finally
    try
      EndUpdate;
    finally
      FBuilding := false;
    end;
  end;
end;

procedure TBGRASVGRasterImageList.RebuildSVG;
begin
  if not Assigned(FSVGSource) or FBuilding or FDestroying or
     (csLoading in ComponentState) then Exit;
  FSVGSource.FWidth := Width;
  FSVGSource.FHeight := Height;
  FSVGSource.QueryRasterize;
  TThread.RemoveQueuedEvents(nil, FSVGSource.RasterizeIfNeeded);
  FSVGSource.RasterizeIfNeeded;
end;

function TBGRASVGRasterImageList.AddSVG(const ASVG: string): integer;
begin
  FBuilding := true;
  try Result := FSVGSource.Add(ASVG);
  finally FBuilding := false; end;
  RebuildSVG;
end;

procedure TBGRASVGRasterImageList.RemoveSVG(AIndex: integer);
begin
  FBuilding := true;
  try FSVGSource.Remove(AIndex);
  finally FBuilding := false; end;
  RebuildSVG;
end;

procedure TBGRASVGRasterImageList.ReplaceSVG(AIndex: integer; const ASVG: string);
begin
  FBuilding := true;
  try FSVGSource.Replace(AIndex, ASVG);
  finally FBuilding := false; end;
  RebuildSVG;
end;

procedure TBGRASVGRasterImageList.ExchangeSVG(AIndex1, AIndex2: integer);
begin
  FBuilding := true;
  try FSVGSource.Exchange(AIndex1, AIndex2);
  finally FBuilding := false; end;
  RebuildSVG;
end;

procedure TBGRASVGRasterImageList.ClearSVG;
begin
  FBuilding := true;
  try
    while SVGCount > 0 do FSVGSource.Remove(SVGCount - 1);
  finally FBuilding := false; end;
  RebuildSVG;
end;

procedure TBGRASVGRasterImageList.RegisterResolutions(const AResolutionWidths: array of integer);
var
  i, j, oldCount: integer;
begin
  if FBuilding or not Assigned(FSVGSource) then
  begin
    inherited RegisterResolutions(AResolutionWidths);
    Exit;
  end;
  for i := 0 to High(AResolutionWidths) do
    if AResolutionWidths[i] <= 0 then
      raise EArgumentException.Create('Resolution widths must be positive');
  for i := 0 to High(AResolutionWidths) do
  begin
    oldCount := Length(FRequestedWidths);
    j := 0;
    while (j < oldCount) and (FRequestedWidths[j] <> AResolutionWidths[i]) do Inc(j);
    if j = oldCount then
    begin
      SetLength(FRequestedWidths, oldCount + 1);
      FRequestedWidths[oldCount] := AResolutionWidths[i];
    end;
  end;
  RebuildSVG;
end;

procedure TBGRASVGRasterImageList.ReadSVGItems(Stream: TStream);
begin
  FSVGSource.ReadData(Stream);
  RebuildSVG;
end;

procedure TBGRASVGRasterImageList.WriteSVGItems(Stream: TStream);
begin
  FSVGSource.WriteData(Stream);
end;

procedure TBGRASVGRasterImageList.DefineProperties(Filer: TFiler);
begin
  inherited DefineProperties(Filer);
  Filer.DefineBinaryProperty('SVGItems', ReadSVGItems, WriteSVGItems, SVGCount > 0);
end;

procedure TBGRASVGRasterImageList.Loaded;
var
  i: integer;
begin
  inherited Loaded;
  if SVGCount > 0 then
  begin
    SetLength(FRequestedWidths, ResolutionCount);
    for i := 0 to ResolutionCount - 1 do
      FRequestedWidths[i] := ResolutionByIndex[i].Width;
    RebuildSVG;
  end;
end;

end.
